site_name: GOSH
nav:
  - Git Open Source Hodler: index.md
  - On-chain Architecture:
    - GOSH Wallet: on-chain-architecture/gosh-wallet.md
    - Organizations - GOSH DAO and SMV: on-chain-architecture/organizations-gosh-dao-and-smv.md
    - GOSH smart contracts: on-chain-architecture/gosh-smart-contracts.md
  - Working with GOSH:
    - GOSH Web: working-with-gosh/gosh-web.md
      ## - Overview: empty.md
      # - DAO: empty.md
      # - Repositories: empty.md
      # - Members: empty.md
      # - Tasks: empty.md
      # - Settings: empty.md
    - Docker Extension: working-with-gosh/docker-extension.md
    - Git Remote Helper: working-with-gosh/git-remote-helper.md
    - AnyTree: working-with-gosh/anytree.md
    - AnyTree Firewall for Telepresence: working-with-gosh/anytree-firewall-for-telepresence.md
    - GOSH AI: working-with-gosh/gosh-ai.md
    #- Build and Sign Images: working-with-gosh/build-and-sign-images.md
    #- Verify Images in Docker Extension: working-with-gosh/verify-images-in-docker-extension.md
  - AnyTree: anytree-all.md
    #- Working with AnyTree: working-with-gosh/anytree.md
    #- Working with AnyTree without GOSH: anytree/anytree-without-gosh.md
  - GOSH Ethereum L2: 
    - Overview: ethereum-L2/overview.md
    - User Guide: ethereum-L2/user-guide.md
  - Integrations:
    - GOSH GitHub Sync: integrations/sync.md
    - GOSH Ethereum L2: integrations/l2.md
    - contracts: integrations/contracts.md
  - Hacks & Grants:
    - Overview: hacks-and-grants/overview.md
    - User Guide: hacks-and-grants/user-guide.md
  - Links: links.md

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true
    - tables

theme:
  logo: images/gosh2.svg
  favicon: images/gosh2.svg
  # name: readthedocs
  name: material
  language: en
  features:
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - content.code.copy
    - content.tooltips
  palette:
    scheme: default
    primary: white
    accent: light blue
  icon:
    annotation: material/arrow-right-circle

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
