name: Deploy

on:
  push:
    branches:
      - main
      - dev
      - ci

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  # default unless branch is 'main'
  BUCKET_NAME: ${{ github.ref == 'refs/heads/main' && 'docs-gosh' || 'staging-docs-gosh' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup policy
        uses: cuchi/jinja2-action@v1.2.1
        with:
          template: .ci/s3/policy.json.j2
          output_file: site/policy.json

      - name: Check if S3 Bucket Exists
        shell: bash
        working-directory: site
        run: |
          if aws s3api head-bucket --bucket "$BUCKET_NAME" ; then
            echo 'Bucket already exists! Just syncing.'
          else
            aws s3api create-bucket --bucket "$BUCKET_NAME" --acl public-read --create-bucket-configuration LocationConstraint="$AWS_DEFAULT_REGION"
            aws s3 website s3://"$BUCKET_NAME" --index-document index.html --error-document index.html
            aws s3api put-bucket-policy --bucket "$BUCKET_NAME" --policy file://policy.json
          fi

      - name: Sync with S3 Bucket
        run: aws s3 sync . s3://"$BUCKET_NAME"

      - name: Create invalidation
        if: github.ref == 'refs/heads/main'
        run: |
          aws cloudfront create-invalidation --distribution-id E38B49XVCTNRVX --paths '/*'
